<?php

/**
 * BaseProfesion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $Empleado
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getNombre()   Returns the current record's "nombre" value
 * @method Doctrine_Collection getEmpleado() Returns the current record's "Empleado" collection
 * @method Profesion           setId()       Sets the current record's "id" value
 * @method Profesion           setNombre()   Sets the current record's "nombre" value
 * @method Profesion           setEmpleado() Sets the current record's "Empleado" collection
 * 
 * @package    inassVreposos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfesion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profesion');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 240, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 240,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Empleado', array(
             'local' => 'id',
             'foreign' => 'profesion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}