<?php

/**
 * Reposos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    inassVreposos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Reposos extends BaseReposos
{

        public function  save(Doctrine_Connection $conn = null, $dian =  null, $diat = null, $diay = null, $diax = null, $diaz  =  null, $diaf = null ) {
        $conn = $conn ? $conn : $this->getTable()->getConnection();
        $conn->beginTransaction();
        try {
            $diax =  strtotime($this->getFinicio());
            $diay =  strtotime($this->getFfin());
            $diaz = ($diax - $diay);
            $dian = ($diaz / 86400);
            $diat = (abs($dian));
            $diau = (floor($diat));
            $this->setDias($diau + 1);
            $ret = parent::save($conn);
            $conn->commit();
            return $ret;
        }  catch (Exception $e) {
            $conn->rollback();
            throw $e;
        }

    }


}