<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/06/25 21:01:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=inassVreposos',
  'username' => 'inassVreposos',
  'password' => '1Zn@s5VR',
  'name' => 'doctrine',
)),);
