default:
  http_metas:
    content-type: text/html

  metas:
    title:        Sistema Automatizado para el Registro y Control de Reposos de los Obreros y Empleados del INASS
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    []

  has_layout:     true
  layout:         login